apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ieim.fullname" . }}-config
  labels:
    {{- include "ieim.labels" . | nindent 4 }}
data:
  {{ .Values.config.fileName }}: |
{{ .Values.config.content | indent 4 }}
