apiVersion: v1
kind: Service
metadata:
  name: {{ include "ieim.fullname" . }}-api
  labels:
    {{- include "ieim.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ieim.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
