{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ieim.serviceAccountName" . }}
  labels:
    {{- include "ieim.labels" . | nindent 4 }}
{{- end }}
